{
  "openapi": "3.0.1",
  "info": {
    "title": "ROOTKey Documentation",
    "description": "Your API of choice for creating, managing, and validating information easily and securely!",
    "termsOfService": "https://www.rootkey.ai/legal/privacy-policy",
    "contact": {
      "name": "ROOTKey",
      "url": "https://www.rootkey.ai/contact",
      "email": "support@rootkey.ai"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "description": "Staging",
      "url": "https://dev-api.rootkey.ai/api-v1/"
    }
  ],
  "security": [
    {
      "x-api-key": []
    }
  ],
  "paths": {
    "/healthz": {
      "get": {
        "tags": [
          "Status"
        ],
        "description": "Check the status of the API on the selected version",
        "security": [],
        "responses": {
          "200": {
            "description": "API status response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "message": "[Auth service]: Status OK"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Version not found",
            "content": {
              "application/json": {
                "example": {
                  "error": 404,
                  "message": "Resource not found"
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/platform/vaults": {
      "post": {
        "tags": [
          "Platform",
          "Vaults"
        ],
        "description": "Create a new vault",
        "requestBody": {
          "description": "Vault creation request payload",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/walletCreationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Wallet created successfully",
            "content": {
              "application/json": {
                "example": {
                  "name": "My first wallet",
                  "description": "First wallet created throught ROOTKey API",
                  "address": ""
                },
                "schema": {
                  "$ref": "#/components/schemas/NewWallet"
                }
              }
            }
          },
          "400": {
            "description": "You have exceeded your usage quota for one or more features.",
            "content": {
              "application/json": {
                "example": {
                  "error": 400,
                  "message": "You have exceeded your usage quota for one or more features.",
                  "docUrl": "https://docs.rootkey.ai/api-reference/errors#usage_limit_exceeded",
                  "errorCode": "usage_limit_exceeded",
                  "timestamp": "2025-05-28T22:07:31.000Z",
                  "details": []
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/platform/vaults/{vaultAddress}": {
      "put": {
        "tags": [
          "Platform",
          "Vaults"
        ],
        "description": "Update a vault",
        "parameters": [
          {
            "in": "path",
            "name": "vaultAddress",
            "description": "The vault address",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Vault update request payload",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VaultUpdateRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Vault updated successfully",
            "content": {
              "application/json": {
                "example": {
                  "name": "My first wallet",
                  "description": "First wallet created throught ROOTKey API",
                  "walletAddress": ""
                },
                "schema": {
                  "$ref": "#/components/schemas/NewWallet"
                }
              }
            }
          },
          "404": {
            "description": "Wallet not found",
            "content": {
              "application/json": {
                "example": {
                  "error": 404,
                  "message": "Wallet not found!"
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Platform",
          "Vaults"
        ],
        "description": "Delete a vault",
        "parameters": [
          {
            "in": "path",
            "name": "vaultAddress",
            "description": "The vault address",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Vault deleted successfully",
            "content": {
              "application/json": {
                "example": {
                  "name": "My first wallet",
                  "description": "First wallet created throught ROOTKey API",
                  "walletAddress": ""
                }
              }
            }
          },
          "404": {
            "description": "Wallet not found",
            "content": {
              "application/json": {
                "example": {
                  "error": 404,
                  "message": "Wallet not found!"
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/platform/vaults/{vaultAddress}/transactions": {
      "post": {
        "tags": [
          "Platform",
          "Vaults"
        ],
        "description": "List transactions relative to a vault",
        "parameters": [
          {
            "in": "path",
            "name": "vaultAddress",
            "description": "The vault address",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Vault transactions list request payload",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VaultTransactionsListRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Transactions list successfully retrieved",
            "content": {
              "application/json": {
                "example": {
                  "hash": "0x1234567890123456789012345678901234567890123456789012345678901234",
                  "from": "0x1234567890123456789012345678901234567890",
                  "to": "0x1234567890123456789012345678901234567890",
                  "value": "1000000000000000000",
                  "timestamp": "2025-05-28T22:07:31.000Z"
                },
                "schema": {
                  "$ref": "#/components/schemas/VaultTransactionsListResponse"
                }
              }
            }
          },
          "404": {
            "description": "Vault not found",
            "content": {
              "application/json": {
                "example": {
                  "errorCode": "resource_not_found",
                  "message": "Vault not found!",
                  "docUrl": "https://docs.rootkey.ai/api-reference/errors#resource_not_found",
                  "timestamp": "2025-05-28T22:07:31.000Z",
                  "details": []
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/platform/files": {
      "get": {
        "tags": [
          "Platform",
          "Files"
        ],
        "description": "List files stored in a vault",
        "parameters": [
          {
            "in": "query",
            "name": "walletAddress",
            "description": "The vault address",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "cursor",
            "description": "The cursor for pagination",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "token",
            "description": "The smart contract address from where is intended to list the files",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Files successfully retrieved",
            "content": {
              "application/json": {
                "example": {
                  "chainId": 80002,
                  "nfts": [
                    {
                      "contractType": "ERC721",
                      "tokenAddress": "0x1234567890123456789012345678901234567890",
                      "tokenId": "1",
                      "uri": "https://example.com/token/1",
                      "name": "ROOT1",
                      "symbol": "RTK",
                      "owner": "0x1234567890123456789012345678901234567890"
                    }
                  ],
                  "nextCursor": ""
                },
                "schema": {
                  "$ref": "#/components/schemas/VaultFilesListResponse"
                }
              }
            }
          },
          "404": {
            "description": "Vault not found",
            "content": {
              "application/json": {
                "example": {
                  "errorCode": "resource_not_found",
                  "message": "Vault not found!",
                  "docUrl": "https://docs.rootkey.ai/api-reference/errors#resource_not_found",
                  "timestamp": "2025-05-28T22:07:31.000Z",
                  "details": []
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Platform",
          "Files"
        ],
        "description": "Create a file to a vault",
        "requestBody": {
          "description": "File creation request payload",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "ownerWallet": {
                    "type": "string"
                  },
                  "fileName": {
                    "type": "string"
                  },
                  "file": {
                    "type": "string",
                    "format": "binary"
                  },
                  "expirationDate": {
                    "type": "string",
                    "format": "date"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Files successfully retrieved",
            "content": {
              "application/json": {
                "example": {
                  "files": [
                    {
                      "chain": "Ethereum",
                      "tokenType": "ERC721",
                      "tokenAddress": "0x1234567890123456789012345678901234567890",
                      "tokenId": "1",
                      "tokenUri": "https://example.com/token/1",
                      "name": "My first NFT",
                      "symbol": "NFT",
                      "ownerOf": "0x1234567890123456789012345678901234567890",
                      "tokenHash": "0x1234567890123456789012345678901234567890"
                    }
                  ],
                  "nextCursor": ""
                },
                "schema": {
                  "$ref": "#/components/schemas/VaultFilesListResponse"
                }
              }
            }
          },
          "404": {
            "description": "Vault not found",
            "content": {
              "application/json": {
                "example": {
                  "errorCode": "resource_not_found",
                  "message": "Vault not found!",
                  "docUrl": "https://docs.rootkey.ai/api-reference/errors#resource_not_found",
                  "timestamp": "2025-05-28T22:07:31.000Z",
                  "details": []
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/platform/files/{fileId}": {
      "get": {
        "tags": [
          "Platform",
          "Files"
        ],
        "description": "List specific file stored in a vault",
        "parameters": [
          {
            "in": "path",
            "name": "fileId",
            "description": "The file id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "File successfully retrieved",
            "content": {
              "application/json": {
                "example": {},
                "schema": {
                  "$ref": "#/components/schemas/ListFileResponse"
                }
              }
            }
          },
          "404": {
            "description": "Vault not found",
            "content": {
              "application/json": {
                "example": {
                  "errorCode": "resource_not_found",
                  "message": "Vault not found!",
                  "docUrl": "https://docs.rootkey.ai/api-reference/errors#resource_not_found",
                  "timestamp": "2025-05-28T22:07:31.000Z",
                  "details": []
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/platform/vaults/reports": {
      "post": {
        "tags": [
          "Platform",
          "Vaults"
        ],
        "requestBody": {
          "description": "",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/walletCreationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Wallet created successfully",
            "content": {
              "application/json": {
                "example": {
                  "name": "My first wallet",
                  "description": "First wallet created throught ROOTKey API",
                  "walletAddress": ""
                },
                "schema": {
                  "$ref": "#/components/schemas/NewWallet"
                }
              }
            }
          },
          "404": {
            "description": "Wallet not found",
            "content": {
              "application/json": {
                "example": {
                  "error": 404,
                  "message": "Wallet not found!"
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "errorCode": {
            "type": "string"
          },
          "details": {
            "type": "string"
          },
          "docUrl": {
            "type": "string"
          },
          "timestamp": {
            "type": "string"
          }
        }
      },
      "Wallet": {
        "required": [
          "walletAddress",
          "privateKey"
        ],
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the wallet",
            "type": "string"
          },
          "description": {
            "description": "The description of the wallet to help you organize your data",
            "type": "string"
          },
          "walletAddress": {
            "description": "The address of the wallet",
            "type": "string"
          },
          "privateKey": {
            "description": "Private Key of the wallet to allow you create, delete and transfer data",
            "type": "string"
          }
        }
      },
      "NewWallet": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the wallet",
            "type": "string"
          },
          "description": {
            "description": "The description of the wallet to help you organize your data",
            "type": "string"
          },
          "address": {
            "description": "The address of the wallet",
            "type": "string"
          }
        }
      },
      "CreateFileRequest": {
        "type": "object",
        "properties": {
          "ownerWallet": {
            "description": "The address of the owner wallet to where the file will be created",
            "type": "string"
          },
          "file": {
            "description": "The file to be created",
            "type": "string",
            "format": "binary"
          },
          "fileName": {
            "description": "The name of the file",
            "type": "string"
          },
          "expirationDate": {
            "description": "The expiration date of the file",
            "type": "string",
            "format": "date"
          }
        }
      },
      "VaultTransactionsListRequest": {
        "type": "object",
        "properties": {
          "cursor": {
            "description": "",
            "type": "string"
          },
          "initialDate": {
            "description": "",
            "type": "string",
            "format": "date"
          },
          "finalDate": {
            "description": "",
            "type": "string",
            "format": "date"
          }
        }
      },
      "VaultTransactionsListResponse": {
        "type": "array",
        "properties": {
          "to": {
            "description": "",
            "type": "string"
          },
          "from": {
            "description": "",
            "type": "string"
          },
          "hash": {
            "description": "",
            "type": "string"
          },
          "transactionFee": {
            "description": "",
            "type": "number"
          },
          "price": {
            "description": "",
            "type": "string"
          },
          "timestamp": {
            "description": "",
            "type": "string"
          }
        }
      },
      "walletCreationRequest": {
        "type": "object",
        "properties": {
          "address": {
            "description": "The name of the wallet",
            "type": "string"
          },
          "name": {
            "description": "The name of the wallet",
            "type": "string"
          },
          "description": {
            "description": "The description of the wallet to help you organize your data",
            "type": "string"
          }
        }
      },
      "smartContractCreationRequest": {
        "type": "object",
        "properties": {
          "ownerWallet": {
            "description": "The name of the wallet",
            "type": "string"
          },
          "type": {
            "description": "The description of the wallet to help you organize your data",
            "type": "string",
            "enum": [
              "rootkey"
            ]
          },
          "subType": {
            "description": "The description of the wallet to help you organize your data",
            "type": "string",
            "enum": [
              "sec1"
            ]
          },
          "privateKey": {
            "description": "The description of the wallet to help you organize your data",
            "type": "string"
          },
          "expirationDate": {
            "description": "The description of the wallet to help you organize your data",
            "type": "string"
          }
        }
      },
      "VaultFilesListRequest": {
        "type": "object",
        "properties": {
          "walletAddress": {
            "description": "The vault address",
            "type": "string"
          },
          "cursor": {
            "description": "The cursor for pagination",
            "type": "string"
          },
          "token": {
            "description": "The smart contract address from where is intended to list the files",
            "type": "string"
          }
        }
      },
      "VaultFilesListResponse": {
        "type": "object",
        "properties": {
          "chainId": {
            "type": "integer"
          },
          "contractType": {
            "type": "string"
          },
          "tokenAddress": {
            "type": "string"
          },
          "tokenId": {
            "type": "string"
          },
          "uri": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "symbol": {
            "type": "string"
          },
          "owner": {
            "type": "string"
          }
        }
      },
      "VaultUpdateRequest": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the wallet",
            "type": "string"
          },
          "description": {
            "description": "The description of the wallet to help you organize your data",
            "type": "string"
          }
        }
      },
      "ListFileResponse": {
        "type": "object"
      }
    },
    "securitySchemes": {
      "x-api-key": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header"
      }
    }
  }
}